name = "VanillaPlus: Create"
author = "hstin"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9eef148011c720db89496b95497d0fb7e8d42321c051b3b657b2b5a39b6d9e31"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.208"
