name = "VanillaPlus: Create"
author = "hstin"
version = "1.2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71f171dceaac2c3557f6125bfd0673a61d13ab8fd3111fd96b84d1d4680c714d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.208"
