name: Build Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pack
          path: |
            pack/
